### ISSUE TITLE
Automatizar tareas, minificado y buenas practicas de performance

### ISSUE THREAD

**Issue by mossmax62** [GDGSantiagoChile/TemarioCurso2015#8]
Desarrollar el tema , crear contenido , etc

**Comment by Angularjschile** [comment]
aplicando esto: https://github.com/johnpapa/angular-styleguide/blob/master/i18n/es-ES.md

**Comment by gpincheiraa** [comment]
Yo tomo este tema. Me basaré en el ejemplo que hagan los demás para luego integrar las prácticas de la guía. Por el momento me centraré en trabajar la presentación.

**Comment by Angularjschile** [comment]
asignado!
